In [137]:
# Import dependencies
import os
import pandas as pd
import requests
from bs4 import BeautifulSoup
from datetime import datetime

In [162]:
def createDataFrame(stat, year):
    # Set url for given year
    url = f'https://www.basketball-reference.com/leagues/NBA_{year}_{stat}.html'
    page = requests.get(url)
    
    # Convert the page html to a soup object
    soup = BeautifulSoup(page.content, 'html.parser')
    
    # Find the sought after table of data
    table = soup.find_all(class_="full_table")

    # Store the headers/column names
    head = soup.find(class_="thead")
    column_names_raw = [head.text for item in head][0]

    # Clean the column_names_raw list
    column_names = column_names_raw.replace("\n",",").split(",")[2:-1]
    
    # Create the dataframe
    players = []

    for i in range(len(table)):
        player_ = []

        for td in table[i].find_all("td"):
            player_.append(td.text)

        players.append(player_)

    df = pd.DataFrame(players, columns=column_names).set_index("Player")

    # Cleaning the player's name from occasional special characters
    df.index = df.index.str.replace('*', "", regex=True)
    
    return df

In [220]:
year = 2008
stat = 'totals'

# Set url for given year
url = f'https://www.basketball-reference.com/leagues/NBA_{year}_{stat}.html'
page = requests.get(url)

# Convert the page html to a soup object
soup = BeautifulSoup(page.content, 'html.parser')

# Find the sought after table of data
table = soup.find_all(class_="full_table")

# Store the headers/column names
head = soup.find(class_="thead")
column_names_raw = [head.text for item in head][0]

# Clean the column_names_raw list
column_names = column_names_raw.replace("\n",",").split(",")[2:-1]

# Create the dataframe
players = []

for i in range(len(table)):
    player_ = []

    for td in table[i].find_all("td"):
        player_.append(td.text)
    
    players.append(player_)

df = pd.DataFrame(players, columns=column_names).set_index("Player")

# Cleaning the player's name from occasional special characters
df.index = df.index.str.replace('*', "", regex=True)

In [229]:
if any(player_[0] in sublist for sublist in players):
    print("yes")

yes

In [230]:
# Get nba players data into dataframes from the year 2000 - 2022
currentYear = datetime.now().year
startYear = 2000
players_totals = {}
players_advanced = {}
players_combined = {}

for year in range(startYear, currentYear+1):
    players_totals[year] = createDataFrame('totals', str(year))
    players_advanced[year] = createDataFrame('advanced', str(year))
    
    # Merge the two dataframes into a new dataframe
    players_combined[year] = players_totals[year].merge(players_advanced[year], how='left', left_on=["Player", "Pos", "Age", "Tm", "G", "MP"], right_on=["Player", "Pos", "Age", "Tm", "G", "MP"])

    # Add a suffix to players with indentical names
#     if len(players_combined[year].index.duplicated()) > 0:
#         for i in range(2, len(players_combined[year].index.duplicated())+2):
#             players_combined[year].index = players_combined[year].index.where(~players_combined[year].index.duplicated(), players_combined[year].index + '_' + str(i))

In [212]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
players_combined[2008].loc["Marcus Williams"]

,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
Player,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Marcus Williams,PG,22,NJN,53,7,854,111,293,.379,54,142,.380,57,151,.377,.471,37,47,.787,14,87,101,140,25,3,75,52,313,11.0,.499,.485,.160,1.9,11.8,6.9,27.8,1.5,0.3,19.3,20.8,,-0.4,0.5,0.2,.009,,-0.8,-1.6,-2.4,-0.1
Marcus Williams,PF-SF,21,TOT,11,0,36,5,20,.250,0,0,,5,20,.250,.250,0,0,,4,8,12,3,1,1,0,3,10,6.8,.250,.000,.000,12.7,25.8,19.2,14.8,1.4,2.1,0.0,25.7,,-0.1,0.0,-0.1,-0.134,,-5.0,-2.7,-7.8,-0.1

In [232]:
# Create a dataframe of individual player stats over the years

individual_stats = {}
roster = ["Jordan Poole"]
years_played = []

for player in roster:
    for year in players_combined:
        if player in players_combined[year].index:
            years_played.append(players_combined[year].loc[[player]]) 
    
individual_stats[player] = pd.concat(years_played)
individual_stats[player]

,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
Player,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Jordan Poole,SG,20,GSW,57,14,1274,167,502,.333,74,265,.279,93,237,.392,.406,95,119,.798,9,109,118,134,35,10,74,94,503,7.2,.454,.528,.237,0.7,9.6,5.0,15.8,1.3,0.7,11.8,21.1,,-1.6,0.4,-1.2,-0.047,,-4.4,-2.2,-6.6,-1.5
Jordan Poole,SG,21,GSW,51,7,988,205,474,.432,97,276,.351,108,198,.545,.535,105,119,.882,15,77,92,99,26,9,51,86,612,15.1,.581,.582,.251,1.6,8.2,5.0,15.4,1.2,0.8,8.8,25.0,,1.1,0.9,1.9,.094,,0.7,-1.2,-0.5,0.4
Jordan Poole,SG,22,GSW,36,30,1060,213,485,.439,92,271,.339,121,214,.565,.534,98,109,.899,8,101,109,120,32,9,85,98,616,14.3,.578,.559,.225,0.9,10.0,5.6,17.8,1.5,0.8,13.8,25.3,,0.9,1.6,2.4,.111,,-0.4,0.0,-0.4,0.4

In [231]:
# Save dataframes to csv
for year in player_combined:
    players_totals[year].to_csv(f'data/player_totals{year}.csv', header=True)
    players_advanced[year].to_csv(f'data/player_advanced{year}.csv', header=True)
    players_combined[year].to_csv(f'data/player_combined{year}.csv', header=True)